// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnyflimmxchtueveaqlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhueWZsaW1teGNodHVldmVhcWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzA4MDQsImV4cCI6MjA3MjY0NjgwNH0.JAR36ikXq37ZlUPHXqVvBTOq6nYjba_1YBs2c6gL3Ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});